# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "Joachim Schuster's blog"
masthead_title: "JS"
email: mail@joachimschuster.de
description: >- # this means to ignore newlines until next config key
  Joachim Schuster's personal thoughts, ideas, insights
  about software development and especially the development of mobile apps.
twitter_username: joachimschuster
github_username: jschuster
github: [metadata] # silence error: 'GitHub Metadata: No GitHub API authentication could be found. Some fields may be missing or have incorrect data.' - see https://github.com/github/pages-gem/issues/399
minimal_mistakes_skin: default
repository: jschuster/jschuster.github.io
search: true
url: https://joachimschuster.de

# Build settings
markdown: kramdown
theme: minimal-mistakes-jekyll
# Outputting
permalink: /posts/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: Europe/Berlin # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages
  - .well-known

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - docker-compose.yml
  - README.md

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-target-blank
  - jekyll-analytics

author:
  name   : "Joachim Schuster"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "Mobile App Developer"
  links:
    # - label: "Website"
    #   icon: "fas fa-fw fa-link"
    #   url: "https://"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/joachimschuster"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/jschuster"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/joachimschuster"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/jschuster"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      show_date: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

jekyll_analytics:
  Plausible:
    domain: 'joachimschuster.de'   # The domain configured in plausible
    source: 'https://plausible.joachimschuster.de/js/plausible.js' # The source of the javascript
